# Generated by Django 4.1.5 on 2024-09-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbrating',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
