# Generated by Django 4.1.5 on 2024-08-22 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=100)),
                ('like', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by', models.ManyToManyField(blank=True, related_name='_following', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
