# Generated by Django 4.1.5 on 2024-08-29 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='like',
        ),
        migrations.AddField(
            model_name='movie',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
