# Generated by Django 4.1.5 on 2024-09-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_imdbrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdbrating',
            field=models.IntegerField(max_length=10),
        ),
    ]
