# Generated by Django 4.1.5 on 2024-08-29 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_like_movie_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
