# Generated by Django 4.1.5 on 2024-09-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_imdbrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbrating',
            new_name='imdb_rating',
        ),
    ]
