# Generated by Django 4.1.5 on 2024-08-29 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='movie',
            name='mylist',
            field=models.ManyToManyField(blank=True, related_name='_mylist', to=settings.AUTH_USER_MODEL),
        ),
    ]
