# Generated by Django 4.1.5 on 2024-09-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_imdbrating_movie_imdb_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
