# Generated by Django 5.0.3 on 2024-09-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_is_bookmarked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
